// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqIg3euK8xXmuqQcDmaNpL5CD-P0s-RbE',
    appId: '1:280439406383:web:8cd34d727ca7fdb8822bda',
    messagingSenderId: '280439406383',
    projectId: 'medialert-16f7d',
    authDomain: 'medialert-16f7d.firebaseapp.com',
    storageBucket: 'medialert-16f7d.firebasestorage.app',
    measurementId: 'G-3429C1TVSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3hQuZRkJCM0nKB7cDoYoPIU_B7GtPnDg',
    appId: '1:280439406383:android:8aec3c071e5c8a6d822bda',
    messagingSenderId: '280439406383',
    projectId: 'medialert-16f7d',
    storageBucket: 'medialert-16f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_0EaoH3qAfFKSx0PGH1wWRVpAOHZIBU',
    appId: '1:280439406383:ios:0a46667563a104a0822bda',
    messagingSenderId: '280439406383',
    projectId: 'medialert-16f7d',
    storageBucket: 'medialert-16f7d.firebasestorage.app',
    iosClientId: '280439406383-7n6l17tbekt2n1kilo4aj1had8vv2org.apps.googleusercontent.com',
    iosBundleId: 'com.example.medialertProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_0EaoH3qAfFKSx0PGH1wWRVpAOHZIBU',
    appId: '1:280439406383:ios:0a46667563a104a0822bda',
    messagingSenderId: '280439406383',
    projectId: 'medialert-16f7d',
    storageBucket: 'medialert-16f7d.firebasestorage.app',
    iosClientId: '280439406383-7n6l17tbekt2n1kilo4aj1had8vv2org.apps.googleusercontent.com',
    iosBundleId: 'com.example.medialertProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqIg3euK8xXmuqQcDmaNpL5CD-P0s-RbE',
    appId: '1:280439406383:web:686fb3a8babbac70822bda',
    messagingSenderId: '280439406383',
    projectId: 'medialert-16f7d',
    authDomain: 'medialert-16f7d.firebaseapp.com',
    storageBucket: 'medialert-16f7d.firebasestorage.app',
    measurementId: 'G-NG47QDK46K',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD3hQuZRkJCM0nKB7cDoYoPIU_B7GtPnDg',
    appId: '1:280439406383:web:8cd34d727ca7fdb8822bda',
    messagingSenderId: '280439406383',
    projectId: 'medialert-16f7d',
    storageBucket: 'medialert-16f7d.firebasestorage.app',
  );
}